name: "Build action: Eloquent"

on:
  push:
    branches: [ eloquent ]
  pull_request:
    branches: [ eloquent ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '17 7 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        ros_distribution: [ eloquent ]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.26
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@0.1.0
      with:
        package-name: "system_modes system_modes_examples"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-mixin-name: coverage-gcc
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info

